apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: kabin-api
  namespace: klage
  labels:
    team: klage
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100M"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "86400"
spec:
  image: {{ image }}
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
  gcp:
    sqlInstances:
      - name: kabin-api
        type: {{ db_type }}
        maintenance:
          day: 1
          hour: 4
        tier: {{ db_tier }}
        diskType: SSD
        highAvailability: {{ db_ha }}
        diskSize: {{ db_size }}
        diskAutoresize: true
        autoBackupHour: 2
        cascadingDelete: false
        databases:
          - name: kabin-api
  azure:
    application:
      enabled: true
      tenant: {{tenant}}
      claims:
        groups:
        {{#each adRoles}}
          - id: {{value}}
        {{/each}}
        extra:
          - NAVident
  port: 7083
  startup:
    failureThreshold: 20
    initialDelay: 30
    path: /internal/health
    periodSeconds: 10
    timeout: 2
  liveness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /internal/health
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      memory: 5000Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  ingresses:
  {{#each ingresses as |ingress|}}
    - {{ingress}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /internal/prometheus
  accessPolicy:
    inbound:
      rules:
      {{#each inboundApplications as |inbound|}}
        - application: {{inbound.application}}
#        {{#if inbound.namespace}}
          namespace: {{inbound.namespace}}
#        {{/if}}
#        {{#if inbound.cluster}}
          cluster: {{inbound.cluster}}
#        {{/if}}
      {{/each}}
    outbound:
      rules:
        - application: kabal-api
        - application: kabal-innstillinger
        - application: klage-lookup
        - application: logging
          namespace: nais-system
      external:
      {{#each externalHosts}}
        - host: {{host}}
      {{/each}}
  envFrom:
    - secret: srvklage-saksbeh
    - secret: pdl-apikey
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: {{springProfile}}
  {{#each envs}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
  {{#each adRoles}}
    - name: {{name}}
      value: {{value}}
  {{/each}}
